databases:
  - name: cazar-db
    databaseName: cazar_ops_hub
    user: cazar_admin
    plan: starter # Paid tier for reliable performance
    ipAllowList: [] # Allow connections from anywhere (configure for security in production)

services:
  - type: web
    name: cazar-ops-hub
    runtime: node
    plan: starter # Paid tier to prevent sleep and ensure reliability
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase:
          name: cazar-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
    rootDir: cazar-ops-hub
    region: oregon # You can change to ohio if preferred 