databases:
  - name: cazar-db
    databaseName: cazar_ops_hub
    user: cazar_admin

services:
  - type: web
    name: cazar-ops-hub
    runtime: node
    plan: starter
    rootDir: ./cazar-ops-hub
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port $PORT --host 0.0.0.0
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        value: postgresql://cazar_admin:7m0bT1rRf0TCnGYeaDOCujeLmcXGsJke@dpg-d25rt60gjchc73acglmg-a.oregon-postgres.render.com/cazar_ops_hub
      - key: VITE_DATABASE_URL
        value: postgresql://cazar_admin:7m0bT1rRf0TCnGYeaDOCujeLmcXGsJke@dpg-d25rt60gjchc73acglmg-a.oregon-postgres.render.com/cazar_ops_hub
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: USE_MOCK_DATA
        value: true
      - key: VITE_USE_MOCK_DATA
        value: true
    healthCheckPath: /
    autoDeploy: true
    region: oregon 
  
  - type: cron
    name: adp-timecard-sync
    runtime: node
    schedule: "0 6 * * 1"  # Every Monday at 6 AM UTC (2 AM EST)
    buildCommand: npm install
    startCommand: node scripts/load_adp_reports.mjs load timecards
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        value: postgresql://cazar_admin:7m0bT1rRf0TCnGYeaDOCujeLmcXGsJke@dpg-d25rt60gjchc73acglmg-a.oregon-postgres.render.com/cazar_ops_hub
      - key: ADP_CLIENT_ID
        sync: false
      - key: ADP_CLIENT_SECRET
        sync: false
      - key: ADP_CERTIFICATE
        sync: false
      - key: ADP_PRIVATE_KEY
        sync: false
    region: oregon